version: "3.9"
services: 
  rfnorm:
    build: .
    image: kuangda/rfnorm
    ports: 
      - "8787:8787"
    environment: 
      - PASSWORD=chad
      - DISABLE_AUTH=true
    volumes: 
      - .:/home/rstudio
